/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIKinect_PKinectV2 */

#ifndef _Included_JNIKinect_PKinectV2
#define _Included_JNIKinect_PKinectV2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIKinect_PKinectV2
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIKinect_PKinectV2_init
  (JNIEnv *, jobject);

/*
 * Class:     JNIKinect_PKinectV2
 * Method:    Nui_GetImage
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_JNIKinect_PKinectV2_Nui_1GetImage
  (JNIEnv *, jobject);

/*
 * Class:     JNIKinect_PKinectV2
 * Method:    Nui_GetDepth
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_JNIKinect_PKinectV2_Nui_1GetDepth
  (JNIEnv *, jobject);

/*
 * Class:     JNIKinect_PKinectV2
 * Method:    Nui_GetMask
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_JNIKinect_PKinectV2_Nui_1GetMask
  (JNIEnv *, jobject);

/*
 * Class:     JNIKinect_PKinectV2
 * Method:    Nui_load
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIKinect_PKinectV2_Nui_1load
  (JNIEnv *, jobject);

/*
 * Class:     JNIKinect_PKinectV2
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIKinect_PKinectV2_update
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
